<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-VO9NQ3U8" failures="0" tests="7" name="com.sadik.dependencyTests.GroupDependency" time="0.016" errors="1" timestamp="2023-08-15T19:04:40 IST" skipped="4">
  <testcase classname="com.sadik.dependencyTests.GroupDependency" name="test36" time="0.000">
    <skipped/>
  </testcase> <!-- test36 -->
  <testcase classname="com.sadik.dependencyTests.GroupDependency" name="test34" time="0.000">
    <skipped/>
  </testcase> <!-- test34 -->
  <testcase classname="com.sadik.dependencyTests.GroupDependency" name="test33" time="0.000">
    <skipped/>
  </testcase> <!-- test33 -->
  <testcase classname="com.sadik.dependencyTests.GroupDependency" name="test29" time="0.012"/>
  <testcase classname="com.sadik.dependencyTests.GroupDependency" name="test35" time="0.000">
    <skipped/>
  </testcase> <!-- test35 -->
  <testcase classname="com.sadik.dependencyTests.GroupDependency" name="test30" time="0.003"/>
  <testcase classname="com.sadik.dependencyTests.GroupDependency" name="test31" time="0.001">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.sadik.dependencyTests.GroupDependency.test31(GroupDependency.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test31 -->
</testsuite> <!-- com.sadik.dependencyTests.GroupDependency -->
